angular.module("mg").config(function($routeProvider){
    $routeProvider
    .when("/",{
        templateUrl:'startview/startview.template.html'
    })
    .when("/login",{
        templateUrl:'./login/login.template.html',
        controller:'login'
    })
    .when("/register",{
        templateUrl:'./registration/register.template.html',
        controller:'register'
    })
    .when("/movies",{
        templateUrl:'./movies/movies.template.html'
    })
    .when("/tv",{
        templateUrl:'./tvShows/tvShows.template.html'
    })
    .when("/tierSelector",{
        templateUrl:'./registration/tierSelector.template.html',
        controller:'TierSelector'
    })
    .when("/watchNow",{
        templateUrl:'./startview/watchnow.template.html',
        controller:'watchNow'
    })
    .when("/userHome",{
        templateUrl:'./startview/Uhome.template.html',
        controller:'watchNow'
    })
    .when("/mediaView",{
        templateUrl:'./mediaView/mediaView.template.html',
        controller:'mediaView'
    });


})